# Assignment 2b

# Damanpreet Singh 000741359

In [10]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
data = pd.read_csv('haberman.data')
data.columns = ["Age","Year-19XX","Positive nodes","Alive/Dead"]     # adding feature headers to the columns
data


Age  Year-19XX  Positive nodes  Alive/Dead
0     30         62               3           1
1     30         65               0           1
2     31         59               2           1
3     31         65               4           1
4     33         58              10           1
..   ...        ...             ...         ...
300   75         62               1           1
301   76         67               0           1
302   77         65               3           1
303   78         65               1           2
304   83         58               2           2

[305 rows x 4 columns]

In [11]:
new_data = data.drop('Year-19XX', axis = 1)
new_data                            ## removed Year column from data as it had no impact on data    

labels = new_data['Alive/Dead']     ## getting classses in dataset


In [21]:
features =  new_data.drop(['Alive/Dead'],axis = 1)     ## gettign features from datasaet

#
features_train,features_test,labels_train,labels_test = train_test_split(features,labels,test_size = 0.75,random_state = 5)

### Hyperparameter Tuning

## 1. Using Test/Traning data split 75/25 and default classifier

In [22]:
run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier()
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)

(array([0.70742358, 0.70742358, 0.72925764, 0.72925764, 0.71615721]),
 0.7179039301310044)

## 2.Using Test/Traning data split 75/25 and tuning classifeir
### criterion='entropy', splitter='best', max_depth=2

In [23]:

run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=2)
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)


(array([0.71615721, 0.71615721, 0.71615721, 0.71615721, 0.71615721]),
 0.7161572052401747)

## 3.Using Test/Traning data split 75/25 and tuning classifier
### criterion='entropy', splitter='reandom', max_depth=6

In [29]:
run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier(criterion='entropy', splitter='random', max_depth=6)
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)

(array([0.71615721, 0.69868996, 0.69432314, 0.70742358, 0.71615721]),
 0.7065502183406114)

## 4.Using Test/Traning data split 75/25 and tuning classifier
### splitter='random', max_depth=2

In [50]:
run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier(splitter='random', max_depth=3)
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)

(array([0.71356784, 0.67839196, 0.71356784, 0.71859296, 0.68844221]),
 0.7025125628140703)

In [41]:
# changing split in data to 65/35
features_train,features_test,labels_train,labels_test = train_test_split(features,labels,test_size = 0.65,random_state = 5)

## 5.Using Test/Traning data split 65/35 and tuning classifier
### default classifier

In [42]:
run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier()
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)

(array([0.67839196, 0.67839196, 0.68844221, 0.69849246, 0.70351759]),
 0.6894472361809045)

## 6.Using Test/Traning data split 65/35 and tuning classifier
### criterion='entropy', splitter='best' and default depth

In [43]:
run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier(criterion='entropy', splitter='best')
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)

(array([0.68844221, 0.69346734, 0.68844221, 0.68341709, 0.68341709]),
 0.6874371859296481)

## 7.Using Test/Traning data split 65/35 and tuning classifier
### splitter='best', max_leaf_nodes=2

In [47]:
run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier(splitter='best', max_leaf_nodes=2)
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)

(array([0.71356784, 0.71356784, 0.71356784, 0.71356784, 0.71356784]),
 0.7135678391959799)

## 8.Using Test/Traning data split 65/35 and tuning classifier
### criterion='entropy'

In [49]:
run_result = np.zeros(5)
counter =0
while counter < 5:
    new_data_clf = DecisionTreeClassifier(criterion='entropy')
    new_data_clf.fit(features_train,labels_train)
    d_predict = new_data_clf.predict(features_test)
    run_result[counter] = accuracy_score(labels_test,d_predict)
    counter = counter+1
    
run_result,np.average(run_result)

(array([0.67839196, 0.68341709, 0.67336683, 0.68341709, 0.68844221]),
 0.6814070351758794)

In [6]:
#data.iloc[0:4,0:3]
#data.loc[0:11,('Alive/Dead')]
#new_data.head()
#new_data['Alive/Dead'].value_counts()
#new_data_clf.get_depth()
#data.describe()